// Generated by CoffeeScript 1.4.0
(function() {
  var settings,
    __hasProp = {}.hasOwnProperty;

  settings = {
    LOCAL_DEPOT_ROOT: "/path/to/asset",
    BUCKETNAME: "________",
    USERNAME: "_________",
    PASSWORD: "__________",
    load: function(module) {
      var key, localSettings, value, _results;
      try {
        localSettings = require(module);
        _results = [];
        for (key in localSettings) {
          if (!__hasProp.call(localSettings, key)) continue;
          value = localSettings[key];
          _results.push(settings[key] = value);
        }
        return _results;
      } catch (e) {

      }
    }
  };

  settings.load("./local_environment");

  module.exports = settings;

}).call(this);
