// Generated by CoffeeScript 1.6.3
(function() {
  var settings,
    __hasProp = {}.hasOwnProperty;

  settings = {
    ASSETS_PATH: "/path/to/asset",
    UPYUN_BUCKETNAME: "________",
    UPYUN_USERNAME: "_________",
    UPYUN_PASSWORD: "__________",
    load: function(module) {
      var e, key, localSettings, value, _results;
      try {
        localSettings = require(module);
        _results = [];
        for (key in localSettings) {
          if (!__hasProp.call(localSettings, key)) continue;
          value = localSettings[key];
          _results.push(settings[key] = value);
        }
        return _results;
      } catch (_error) {
        e = _error;
      }
    }
  };

  settings.load("./local_environment");

  module.exports = settings;

}).call(this);
