// Generated by CoffeeScript 1.6.3
(function() {
  var CMD_SYNC_AMF, CMD_SYNC_GRAPHICS, CMD_SYNC_TIMESTAMPE, CURRENT_JOB, JOB_SYNC_ASSET, KV_CLIENTS, app, io, logger, runJob, server, spawn, util;

  app = require('express')();

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  util = require('util');

  logger = require('dev-logger');

  spawn = require('child_process').spawn;

  CURRENT_JOB = null;

  JOB_SYNC_ASSET = ["" + __dirname + "/node_modules/upyun-assets-syncer/bin/upsyncer.coffee"];

  CMD_SYNC_GRAPHICS = 'sync_graphics';

  CMD_SYNC_AMF = 'sync_amf';

  CMD_SYNC_TIMESTAMPE = 'sync_timestamp';

  KV_CLIENTS = {};

  server.listen(8088);

  app.get('/', function(req, res) {
    return res.sendfile(__dirname + '/index.html');
  });

  runJob = function(configj) {
    if (IS_BUSY) {
      io.sockets.emit('error', {
        contennt: "当前正有一个任务在进行，请等待当前任务完成后在进行操作"
      });
    }
  };

  io.sockets.on('connection', function(socket) {
    KV_CLIENTS[socket.id] = socket;
    io.sockets.emit('log', {
      contennt: "client " + socket.id + " connected"
    });
    return socket.on('action', function(data) {
      switch (data.cmd) {
        case CMD_SYNC_GRAPHICS:
          console.log(data.cmd);
          break;
        case CMD_SYNC_AMF:
          console.log(data.cmd);
          break;
        case CMD_SYNC_TIMESTAMPE:
          console.log(data.cmd);
      }
    });
  });

  return;

}).call(this);
